### ISSUE TITLE
Extraneous/misplaced errors under merlin + OCaml 4.04.0

### ISSUE THREAD

**Issue by hcarty** [zepalmer/ocaml-monadic#3]
Using OCaml 4.04.0+flambda and merlin 2.5.3 the following shows an error at the start of the file in addition to the actual error on line 4.  When compiling directly only the error on line 4 is reported.

I'm not sure if this is an issue with ocaml-monadic or merlin.

.merlin:
```
PKG ocaml-monadic
S .
```

test.ml:
```ocaml
let bind x =
  match x with
  | None -> None
  | Some x -> f x

let () =
  let result =
    let%bind y = Some "hello" in
    Some y
  in
  ignore result
```

**Comment by zepalmer** [comment]
I just performed a series of tests with different OCaml compilers from OPAM:

* 4.02.3
* 4.03.0
* 4.04.0
* 4.04.0+flambda

In each case, I used Merlin 2.5.3.  I observed the same behavior in each case: Merlin produced two error messages.  As reported by Atom (since I use the `ocaml-merlin` Atom package), the messages were:

* ```This function has type 'a option -> 'b option It is applied to too many arguments; maybe you forgot a `;'.```
* `Unbound value f at line 4 col 15`

I presume the first error message to be the one that is giving you concern.  This message arises because the provided test code desugars to

```
let bind x =
  match x with
  | None -> None
  | Some x -> f x

let () =
  let result =
    bind (Some "hello") (fun y  -> Some y)
  in
  ignore result
```

Here, there are two error messages: one at line 4 (where we use the unbound `f`) and one at line 8 (where we invoke `bind` with too many arguments).  Both of these assessments are correct, although the one on line 8 is coming from generated code and so somewhat more difficult to comprehend.

Both the OCaml compiler and Merlin essentially only analyze this code after it has been desugared, so I'm not sure that there's a way for the `ocaml-monadic` plugin to do anything to pretty up that particular error.  I'm open to suggestions, though.  :)

**Comment by hcarty** [comment]
My concern isn't the error - that part makes sense!  My concern is the location reporting.  On my system I get the second error reported at the start of the file - it seems to be falling back to the default location.  Thanks for looking into this!

Do you get the correct line 8 location from inside Atom?  I'm using vim, maybe there is a plugin mismatch or related issue.

**Comment by zepalmer** [comment]
I get the correct line on the *desugared* code, but I don't get any line information at all for the sugared code.  I think my Atom plugin is getting the same information as your vim plugin is: no line information is being conveyed for that error.  (In this case, the Atom plugin doesn't report it at the top of the file; it just doesn't report a location at all.)

If we compile from the command line, we only get:

```
File "test.ml", line 4, characters 14-15:
Error: Unbound value f
```

That seems weird to me; it's as if the compiler is suppressing the other error either because (a) the unbound value is from an earlier class or (b) generated code errors are suppressed under some policy.  Either way, this isn't the same result as Merlin, so it might be that Merlin just doesn't handle errors in generated code very well.

In either case, I'm not certain there's much I can do as a PPX plugin writer to address this.  I'll leave the issue open for now, though, in case anyone happens by it and can educate me on the matter.  :)

Thank you for reporting and for giving a clear test case to demonstrate the behavior.  :-D

**Comment by hcarty** [comment]
@let-def @trefis Do you have any insight into what could cause this?

**Comment by zepalmer** [comment]
I do use `ppx_tools.metaquot` to generate the ASTs.  I'm not sure if that would have an impact on the resulting position data.

**Comment by hcarty** [comment]
I use `ppx_tools.metaquot` in ppx_defer as well but I haven't been able to recreate this issue using it: https://github.com/hcarty/ppx_defer/blob/master/src/ppx_defer.ml

This code, with `ppx_defer` loaded in merlin:
```ocaml
let () =
  [%defer f];
  ()
```
only reports the `Unbound value f` error on line 2 column 11 (the correct location).  Maybe there's something useful/helpful in ppx_defer's approach?

**Comment by let-def** [comment]
The first difference is that merlin doesn't stop after first semantic error, it continues until the end of file. Hence it reports a second error.

The second error is due to the type merlin inferred for bind: it was not able to type the full body, but it was able to get that the argument is an option because of the match and the result an option because of the first branch.

The second error has no location because the rewriter didn't provide any. In the example from hcarty the error is in user code (`f`), not in generated code, so it has a location.
With monadic rewriter the error is in the bind application, which was generated without location.

You can give a location to ppx_metaquot generated code. Actually, you should. If you remove the first type error, you can make ocaml generate an error without location with your rewriter:

```
$ cat test.ml
let _ =
  let%bind y = "lol" in
  None
$ ocamlfind c -package ocaml-monadic -c test.ml 
File "_none_", line 1:
Error: Unbound value bind
```

So the problem is not merlin specific, but you triggered it with merlin only :).
To provide a location to ppx_metaquot, see https://github.com/alainfrisch/ppx_tools/blob/master/ppx_metaquot.ml#L28.
You can experiment a bit with appropriate locations, I would suggest giving the whole location of the let binding to the application (`bind x f`) and the location of the `%bind` extension to the bind occurrence (`bind`).

**Comment by let-def** [comment]
Actually, if you fix the type error, you get the same second error in ocaml:
```ocaml
let bind x =
  match x with
  | None -> None
  | Some x -> Some x

let () =
  let result =
    let%bind y = Some "hello" in
    Some y
  in
  ignore result
```

```
File "_none_", line 1:
Error: This function has type 'a option -> 'a option
       It is applied to too many arguments; maybe you forgot a `;'.
```

**Comment by zepalmer** [comment]
Thanks for the `ppx_tools.metaquot` info; I'll try to add some more reasonable locations in the future.  I had thought that the location of generated code should default to the use site of the PPX extension, but I suppose that this is not the case.  I appreciate the tip!

**Comment by hcarty** [comment]
I was able to test this today and the problem seems to be fixed!  Thank you very much for working on this.

**Comment by zepalmer** [comment]
Hooray!  Thank you for testing it.
